<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <RootNamespace>View</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<AssemblyName>DrakohnonLanguageTranslator</AssemblyName>
    <ApplicationIcon>Assets\favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TranslatorLogic\TranslatorLogic.csproj" />
  </ItemGroup>

</Project>
